### ISSUE TITLE
Cannot change the scale/size of the icons Independently

### ISSUE THREAD

**Issue by DeterHope** [FuryBaguette/SwitchLayoutEditor#26]
i tried to create a custom nxtheme , then i tried to change the scale and the size Independently (like: icons 00 , Scale : 0,5;0,5 and icons 01: Scale: 1;1) but when i load it in my switch : the size and the scale doesn't changed.... 

Thank you for your response and have a nice day ;)

**Comment by DeterHope** [comment]
please a response ?

**Comment by exelix11** [comment]
I don't actively work on layout editing anymore and don't know how to answer your question. Usually when you want to achieve some effect you look at one of the built-in layouts and try to understand how they managed to do it.

In general not all the properties work as you expect since the home menu also adds its own hardcoded modifiers on top of the layout engine so it may overwrite specific changes it doesn't like.. Unfortunately, the only way of knowing is by trial and error.

**Comment by DeterHope** [comment]
Thanks I will maybe publish a tutorial if i find how to do it
